export const HOBBIES_LIST = [
  { name: 'Photography', icon: '📷' },
  { name: 'Reading', icon: '📚' },
  { name: 'Gaming', icon: '🎮' },
  { name: 'Cooking', icon: '🍳' },
  { name: 'Baking', icon: '🍰' },
  { name: 'Painting', icon: '🎨' },
  { name: 'Drawing', icon: '✏️' },
  { name: 'Writing', icon: '✍️' },
  { name: 'Coding', icon: '💻' },
  { name: 'Traveling', icon: '✈️' },
  { name: 'Hiking', icon: '🥾' },
  { name: 'Running', icon: '🏃' },
  { name: 'Cycling', icon: '🚲' },
  { name: 'Swimming', icon: '🏊' },
  { name: 'Yoga', icon: '🧘' },
  { name: 'Meditation', icon: '🧘‍♀️' },
  { name: 'Dancing', icon: '💃' },
  { name: 'Singing', icon: '🎤' },
  { name: 'Guitar', icon: '🎸' },
  { name: 'Piano', icon: '🎹' },
  { name: 'Violin', icon: '🎻' },
  { name: 'Drums', icon: '🥁' },
  { name: 'Gardening', icon: '🌱' },
  { name: 'Fishing', icon: '🎣' },
  { name: 'Knitting', icon: '🧶' },
  { name: 'Sewing', icon: '🧵' },
  { name: 'Woodworking', icon: '🪵' },
  { name: 'Pottery', icon: '🏺' },
  { name: 'Calligraphy', icon: '✒️' },
  { name: 'Movies', icon: '🎬' },
  { name: 'TV Shows', icon: '📺' },
  { name: 'Anime', icon: '🎌' },
  { name: 'Manga', icon: '📖' },
  { name: 'Podcasts', icon: '🎙️' },
  { name: 'Board Games', icon: '🎲' },
  { name: 'Card Games', icon: '🃏' },
  { name: 'Chess', icon: '♟️' },
  { name: 'Puzzles', icon: '🧩' },
  { name: 'Volunteering', icon: '🤝' },
  { name: 'Learning Languages', icon: '🗣️' },
  { name: 'Investing', icon: '📈' },
  { name: 'DIY Projects', icon: '🛠️' },
  { name: 'Astronomy', icon: '🔭' },
  { name: 'Bird Watching', icon: '🐦' },
  { name: 'Rock Climbing', icon: '🧗' },
  { name: 'Skiing', icon: '⛷️' },
  { name: 'Snowboarding', icon: '🏂' },
  { name: 'Skateboarding', icon: '🛹' },
  { name: 'Surfing', icon: '🏄' },
  { name: 'Kayaking', icon: '🛶' },
  { name: 'Sailing', icon: '⛵' },
  { name: 'Archery', icon: '🏹' },
  { name: 'Fencing', icon: '🤺' },
  { name: 'Martial Arts', icon: '🥋' },
  { name: 'Boxing', icon: '🥊' },
  { name: 'Wrestling', icon: '🤼' },
  { name: 'Gymnastics', icon: '🤸' },
  { name: 'Weightlifting', icon: '🏋️' },
  { name: 'Tennis', icon: '🎾' },
  { name: 'Badminton', icon: '🏸' },
  { name: 'Cricket', icon: '🏏' },
  { name: 'Baseball', icon: '⚾' },
  { name: 'Basketball', icon: '🏀' },
  { name: 'Football (Soccer)', icon: '⚽' },
  { name: 'American Football', icon: '🏈' },
  { name: 'Rugby', icon: '🏉' },
  { name: 'Volleyball', icon: '🏐' },
  { name: 'Table Tennis', icon: '🏓' },
  { name: 'Billiards', icon: '🎱' },
  { name: 'Bowling', icon: '🎳' },
  { name: 'Darts', icon: '🎯' },
  { name: 'Golf', icon: '⛳' },
  { name: 'Ice Hockey', icon: '🏒' },
  { name: 'Field Hockey', icon: '🏑' },
  { name: 'Lacrosse', icon: '🥍' },
  { name: 'Handball', icon: '🤾' },
  { name: 'Water Polo', icon: '🤽' },
  { name: 'Scuba Diving', icon: '🤿' },
  { name: 'Snorkeling', icon: '🤿' },
  { name: 'Origami', icon: '🏮' },
  { name: 'Beatboxing', icon: '🗣️' },
  { name: 'DJing', icon: '🎧' },
  { name: 'Magic', icon: '🎩' },
  { name: 'Juggling', icon: '🤹' },
  { name: 'Stand-up Comedy', icon: '😂' },
  { name: 'Improv', icon: '🎭' },
  { name: 'Acting', icon: '🎭' },
  { name: 'Filmmaking', icon: '🎬' },
  { name: 'Animation', icon: '✍️' },
  { name: 'Graphic Design', icon: '🎨' },
  { name: 'Web Design', icon: '💻' },
  { name: 'Game Development', icon: '👾' },
  { name: 'App Development', icon: '📱' },
  { name: 'Robotics', icon: '🤖' },
  { name: '3D Printing', icon: '🖨️' },
  { name: 'Blogging', icon: '📝' },
  { name: 'Vlogging', icon: '📹' },
  { name: 'Streaming', icon: '🔴' },
  { name: 'Cosplaying', icon: '🦸' },
  { name: 'LARPing', icon: '⚔️' },
  { name: 'Geocaching', icon: '📍' },
  { name: 'Escape Rooms', icon: '🔑' },
  { name: 'Collecting', icon: '📦' },
  { name: 'Antiquing', icon: '🕰️' },
  { name: 'Thrifting', icon: '👕' },
  { name: 'Couponing', icon: '✂️' },
  { name: 'Genealogy', icon: '🌳' },
  { name: 'Astrology', icon: '✨' },
  { name: 'Tarot Reading', icon: '🔮' },
  { name: 'Foraging', icon: '🍄' },
  { name: 'Fermenting', icon: ' fermenting_jar' },
  { name: 'Homebrewing', icon: '🍺' },
  { name: 'Winemaking', icon: '🍷' },
  { name: 'Mixology', icon: '🍸' },
  { name: 'Coffee Roasting', icon: '☕' },
  { name: 'Tea Tasting', icon: '🍵' },
  { name: 'Cheese Making', icon: '🧀' },
  { name: 'Bread Making', icon: '🥖' },
  { name: 'Beekeeping', icon: '🐝' },
  { name: 'Candle Making', icon: '🕯️' },
  { name: 'Soap Making', icon: '🧼' },
  { name: 'Perfume Making', icon: '👃' },
  { name: 'Jewelry Making', icon: '💍' },
  { name: 'Flower Arranging', icon: '💐' },
  { name: 'Terrarium Making', icon: '🌿' },
  { name: 'Kokedama', icon: '🎍' },
  { name: 'Bonsai', icon: '🌳' },
  { name: 'Aquascaping', icon: '🐠' },
  { name: 'Fishkeeping', icon: '🐠' },
  { name: 'Ant Keeping', icon: '🐜' },
  { name: 'Reptile Keeping', icon: '🐍' },
  { name: 'Model Building', icon: '✈️' },
  { name: 'LEGO', icon: '🧱' },
  { name: 'RC Cars', icon: '🚗' },
  { name: 'Drones', icon: '🚁' },
  { name: 'Kite Flying', icon: '🪁' }
]; 