export const HOBBIES_LIST = [
  // Music-specific hobbies
  { name: 'Piano', icon: '🎹' },
  { name: 'Guitar', icon: '🎸' },
  { name: 'Violin', icon: '🎻' },
  { name: 'Drums', icon: '🥁' },
  { name: 'Saxophone', icon: '🎷' },
  { name: 'Flute', icon: '🎼' },
  { name: 'Composing', icon: '🎵' },
  { name: 'Music Production', icon: '🎧' },
  { name: 'DJing', icon: '💿' },
  { name: 'Singing', icon: '🎤' },
  { name: 'Music Theory', icon: '📚' },
  { name: 'Sound Design', icon: '🎛️' },
  { name: 'Live Performance', icon: '🎭' },
  { name: 'Studio Recording', icon: '🎙️' },
  { name: 'Music Arrangement', icon: '🎼' },
  
  // General hobbies
  { name: 'Reading', icon: '📚' },
  { name: 'Writing', icon: '✍️' },
  { name: 'Photography', icon: '📸' },
  { name: 'Cooking', icon: '👨‍🍳' },
  { name: 'Travel', icon: '✈️' },
  { name: 'Hiking', icon: '🏔️' },
  { name: 'Swimming', icon: '🏊' },
  { name: 'Cycling', icon: '🚴' },
  { name: 'Yoga', icon: '🧘' },
  { name: 'Meditation', icon: '🧘‍♀️' },
  { name: 'Painting', icon: '🎨' },
  { name: 'Drawing', icon: '✏️' },
  { name: 'Gaming', icon: '🎮' },
  { name: 'Movies', icon: '🎬' },
  { name: 'Music', icon: '🎵' },
  { name: 'Dancing', icon: '💃' },
  { name: 'Fitness', icon: '💪' },
  { name: 'Gardening', icon: '🌱' },
  { name: 'Chess', icon: '♟️' },
  { name: 'Puzzles', icon: '🧩' },
  { name: 'Collecting', icon: '📦' },
  { name: 'DIY', icon: '🔧' },
  { name: 'Volunteering', icon: '🤝' },
  { name: 'Learning', icon: '🎓' },
  { name: 'Networking', icon: '🤝' },
  { name: 'Blogging', icon: '📝' },
  { name: 'Podcasting', icon: '🎙️' },
  { name: 'Vlogging', icon: '📹' },
  { name: 'Social Media', icon: '📱' },
  { name: 'Coding', icon: '💻' },
  { name: 'Design', icon: '🎨' },
  { name: 'Architecture', icon: '🏗️' },
  { name: 'Fashion', icon: '👗' },
  { name: 'Beauty', icon: '💄' },
  { name: 'Sports', icon: '⚽' },
  { name: 'Martial Arts', icon: '🥋' },
  { name: 'Rock Climbing', icon: '🧗' },
  { name: 'Surfing', icon: '🏄' },
  { name: 'Skiing', icon: '⛷️' },
  { name: 'Snowboarding', icon: '🏂' },
  { name: 'Fishing', icon: '🎣' },
  { name: 'Hunting', icon: '🏹' },
  { name: 'Camping', icon: '⛺' },
  { name: 'Bird Watching', icon: '🐦' },
  { name: 'Astronomy', icon: '🔭' },
  { name: 'Archaeology', icon: '🏺' },
  { name: 'Genealogy', icon: '👨‍👩‍👧‍👦' },
  { name: 'Calligraphy', icon: '✒️' },
  { name: 'Origami', icon: '🦢' },
  { name: 'Knitting', icon: '🧶' },
  { name: 'Crochet', icon: '🧶' },
  { name: 'Sewing', icon: '🧵' },
  { name: 'Woodworking', icon: '🪚' },
  { name: 'Metalworking', icon: '⚒️' },
  { name: 'Pottery', icon: '🏺' },
  { name: 'Glassblowing', icon: '🔥' },
  { name: 'Jewelry Making', icon: '💍' },
  { name: 'Candle Making', icon: '🕯️' },
  { name: 'Soap Making', icon: '🧼' },
  { name: 'Brewing', icon: '🍺' },
  { name: 'Wine Making', icon: '🍷' },
  { name: 'Baking', icon: '🍰' },
  { name: 'Fermentation', icon: '🥬' },
  { name: 'Aquaponics', icon: '🐟' },
  { name: 'Beekeeping', icon: '🐝' },
  { name: 'Chicken Keeping', icon: '🐔' },
  { name: 'Horse Riding', icon: '🐎' },
  { name: 'Dog Training', icon: '🐕' },
  { name: 'Cat Care', icon: '🐱' },
  { name: 'Reptile Keeping', icon: '🦎' },
  { name: 'Fish Keeping', icon: '🐠' },
  { name: 'Bird Keeping', icon: '🦜' },
  { name: 'Hamster Care', icon: '🐹' },
  { name: 'Rabbit Care', icon: '🐰' },
  { name: 'Guinea Pig Care', icon: '🐹' },
  { name: 'Ferret Care', icon: '🦦' },
  { name: 'Sugar Glider Care', icon: '🦇' },
  { name: 'Hedgehog Care', icon: '🦔' },
  { name: 'Chinchilla Care', icon: '🐭' },
  { name: 'Gerbil Care', icon: '🐹' },
  { name: 'Rat Care', icon: '🐀' },
  { name: 'Mouse Care', icon: '🐁' },
  { name: 'Hamster Care', icon: '🐹' },
  { name: 'Guinea Pig Care', icon: '🐹' },
  { name: 'Rabbit Care', icon: '🐰' },
  { name: 'Bird Keeping', icon: '🦜' },
  { name: 'Fish Keeping', icon: '🐠' },
  { name: 'Reptile Keeping', icon: '🦎' },
  { name: 'Cat Care', icon: '🐱' },
  { name: 'Dog Training', icon: '🐕' },
  { name: 'Horse Riding', icon: '🐎' },
  { name: 'Chicken Keeping', icon: '🐔' },
  { name: 'Beekeeping', icon: '🐝' },
  { name: 'Aquaponics', icon: '🐟' },
  { name: 'Fermentation', icon: '🥬' },
  { name: 'Baking', icon: '🍰' },
  { name: 'Wine Making', icon: '🍷' },
  { name: 'Brewing', icon: '🍺' },
  { name: 'Soap Making', icon: '🧼' },
  { name: 'Candle Making', icon: '🕯️' },
  { name: 'Jewelry Making', icon: '💍' },
  { name: 'Glassblowing', icon: '🔥' },
  { name: 'Pottery', icon: '🏺' },
  { name: 'Metalworking', icon: '⚒️' },
  { name: 'Woodworking', icon: '🪚' },
  { name: 'Sewing', icon: '🧵' },
  { name: 'Crochet', icon: '🧶' },
  { name: 'Knitting', icon: '🧶' },
  { name: 'Origami', icon: '🦢' },
  { name: 'Calligraphy', icon: '✒️' },
  { name: 'Genealogy', icon: '👨‍👩‍👧‍👦' },
  { name: 'Archaeology', icon: '🏺' },
  { name: 'Astronomy', icon: '🔭' },
  { name: 'Bird Watching', icon: '🐦' },
  { name: 'Camping', icon: '⛺' },
  { name: 'Hunting', icon: '🏹' },
  { name: 'Fishing', icon: '🎣' },
  { name: 'Snowboarding', icon: '🏂' },
  { name: 'Skiing', icon: '⛷️' },
  { name: 'Surfing', icon: '🏄' },
  { name: 'Rock Climbing', icon: '🧗' },
  { name: 'Martial Arts', icon: '🥋' },
  { name: 'Sports', icon: '⚽' },
  { name: 'Beauty', icon: '💄' },
  { name: 'Fashion', icon: '👗' },
  { name: 'Architecture', icon: '🏗️' },
  { name: 'Design', icon: '🎨' },
  { name: 'Coding', icon: '💻' },
  { name: 'Social Media', icon: '📱' },
  { name: 'Vlogging', icon: '📹' },
  { name: 'Podcasting', icon: '🎙️' },
  { name: 'Blogging', icon: '📝' },
  { name: 'Networking', icon: '🤝' },
  { name: 'Learning', icon: '🎓' },
  { name: 'Volunteering', icon: '🤝' },
  { name: 'DIY', icon: '🔧' },
  { name: 'Collecting', icon: '📦' },
  { name: 'Puzzles', icon: '🧩' },
  { name: 'Chess', icon: '♟️' },
  { name: 'Gardening', icon: '🌱' },
  { name: 'Fitness', icon: '💪' },
  { name: 'Dancing', icon: '💃' },
  { name: 'Music', icon: '🎵' },
  { name: 'Movies', icon: '🎬' },
  { name: 'Gaming', icon: '🎮' },
  { name: 'Drawing', icon: '✏️' },
  { name: 'Painting', icon: '🎨' },
  { name: 'Meditation', icon: '🧘‍♀️' },
  { name: 'Yoga', icon: '🧘' },
  { name: 'Cycling', icon: '🚴' },
  { name: 'Swimming', icon: '🏊' },
  { name: 'Hiking', icon: '🏔️' },
  { name: 'Travel', icon: '✈️' },
  { name: 'Cooking', icon: '👨‍🍳' },
  { name: 'Photography', icon: '📸' },
  { name: 'Writing', icon: '✍️' },
  { name: 'Reading', icon: '📚' }
]; 