export const HOBBIES_LIST = [
  { name: 'Reading', icon: '📚' },
  { name: 'Gaming', icon: '🎮' },
  { name: 'Cooking', icon: '🍳' },
  { name: 'Hiking', icon: '🏞️' },
  { name: 'Traveling', icon: '✈️' },
  { name: 'Photography', icon: '📷' },
  { name: 'Painting', icon: '🎨' },
  { name: 'Writing', icon: '✍️' },
  { name: 'Coding', icon: '💻' },
  { name: 'Music', icon: '🎵' },
  { name: 'Movies', icon: '🎬' },
  { name: 'Sports', icon: '⚽' },
  { name: 'Fitness', icon: '💪' },
  { name: 'Dancing', icon: '💃' },
  { name: 'Gardening', icon: '🌱' },
  { name: 'Fishing', icon: '🎣' },
  { name: 'Yoga', icon: '🧘' },
  { name: 'Meditation', icon: '🧘‍♀️' },
  { name: 'Knitting', icon: '🧶' },
  { name: 'Woodworking', icon: '🔨' },
  { name: 'Volunteering', icon: '🤝' },
  { name: 'Board Games', icon: '🎲' },
  { name: 'Cycling', icon: '🚴' },
  { name: 'Running', icon: '🏃' },
  { name: 'Swimming', icon: '🏊' },
  { name: 'Skiing', icon: '🎿' },
  { name: 'Snowboarding', icon: '🏂' },
  { name: 'Surfing', icon: '🏄' },
  { name: 'Climbing', icon: '🧗' },
  { name: 'Archery', icon: '🏹' },
  { name: 'Baking', icon: '🍰' },
  { name: 'Pottery', icon: '🏺' },
  { name: 'Calligraphy', icon: '✒️' },
  { name: 'Bird Watching', icon: '🐦' },
  { name: 'Stargazing', icon: '🔭' },
  { name: 'DIY Projects', icon: '🛠️' },
  { name: 'Podcasting', icon: '🎙️' },
  { name: 'Streaming', icon: '📺' },
  { name: 'Collecting', icon: '📦' },
  { name: 'Chess', icon: '♟️' },
]; 